# Generated by Django 4.2 on 2024-07-08 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(default='', max_length=500)),
                ('gender', models.CharField(choices=[('', ''), ('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=50)),
                ('relationship_status', models.CharField(choices=[('', ''), ('NEVER MARRIED', 'Never Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], default='NEVER MARRIED', max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
                ('citylat', models.DecimalField(decimal_places=6, default='-2.0180319', max_digits=9)),
                ('citylong', models.DecimalField(decimal_places=6, default='52.5525525', max_digits=9)),
                ('birth_date', models.DateField(default='1990-01-01', null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
