# Generated by Django 4.2 on 2024-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='citylat',
            field=models.DecimalField(decimal_places=6, default='43.06667', max_digits=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='citylong',
            field=models.DecimalField(decimal_places=6, default='141.35', max_digits=9),
        ),
    ]
